name: Pokemon Pre-release
on:
  push:
    branches:
      - 'Pokemon-dev'

jobs:
  prerelease:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: read
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: Automated Version Bump
        id: version-bump
        uses: phips28/gh-action-bump-version@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag-prefix: v
          skip-tag: 'true'
          default: prerelease
          rc-wording: 'fix,refactor'
      - name: Check bumped version
        id: package-version
        run: echo "version bumped to ${{ steps.version-bump.outputs.newTag }}" && echo "currentVersion=${{ steps.version-bump.outputs.newTag }}" >> $GITHUB_OUTPUT
      - name: Pre-release
        if: ${{ steps.package-version.outputs.currentVersion != '' }}
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: 'true'
          automatic_release_tag: 'latest-rc'
